import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next';

// export const getStaticProps: GetStaticProps = async () => {
//   const allPostsData = getSortedPostsData();

//   return {
//     props: {
//       allPostsData,
//     },
//   };
// };

// export const getServerSideProps: GetServerSideProps = async ctx => {
//   console.log('ctx', ctx);
//   const allPostsData = getSortedPostsData();

//   return {
//     props: {
//       allPostsData,
//       ctx,
//     },
//   };
// };

export default function Home(props) {
  console.log(props);
  return (
    <div className={styles.container}>
      <Head>
        <title>Recipe Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row">
        <h1 className="text-center text-xs pt-4 m-0">Recipe Builder</h1>
        <p className="text-center text-xs pt-4 m-0">
          This is test text to test Tailwind
        </p>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
      </div>
      <ul>
        {/* {props.allPostsData.map(({ id, date, title }) => (
          <li key={id}>
            {title}
            <br />
            {id}
            <br />
            {date}
          </li>
        ))} */}
      </ul>
    </div>
  );
}
